apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: es03
  name: es03
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es03
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: es03
    spec:
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: esdata03
          mountPath: /usr/share/elasticsearch/data
      - name: increase-the-vm-max-map-count
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true 
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: cluster.initial_master_nodes
              value: es01,es02,es03
            - name: cluster.name
              value: es-docker-cluster
            - name: discovery.seed_hosts
              value: es01,es02
            - name: node.name
              value: es03
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          name: es03  
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata03 
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-staging-v1-es          
      restartPolicy: Always
      volumes:
        - name: esdata03
status: {}
