apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nodered-service
  name: nodered
spec:
  ports:
    - name: "1880"
      port: 1880
      targetPort: 1880
  selector:
    io.kompose.service: nodered-service
status:
  loadBalancer: {}
