apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nodered
  name: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: nodered
    spec:
      containers:
        - image: nodered/node-red:latest
          name: nodered
          ports:
            - containerPort: 1880
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: nodered-claim0
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-staging-v1-services
      restartPolicy: Always
      volumes:
           - name: nodered-claim0
status: {}
